---
- name: "Simulate Deployment to Suricata Node"
  hosts: suricata
  tasks:
    - name: "Step 1: Copy Exporter Script to /opt/"
      debug:
        msg: "File log_exporter.py copied successfully."

    - name: "Step 2: Restart Suricata Service"
      debug:
        msg: "Suricata service restarted successfully."

- name: "Simulate Deployment to Honeypot Node"
  hosts: honeypot
  tasks:
    - name: "Step 1: Deploy Trap Scripts"
      debug:
        msg: "Trap scripts deployed successfully."
